{ pkgs, ... }:

{
  environment.systemPackages = [
    pkgs.vim
    pkgs.firefox
    pkgs.firefox-wayland
    pkgs.curl
    pkgs.htop
    pkgs.hyprland
    pkgs.kitty
    pkgs.foot
    pkgs.pciutils
    pkgs.waybar
    pkgs.hyprpaper
    pkgs.wofi
    pkgs.neovim
    pkgs.xdg-utils
    pkgs.xdg-desktop-portal
    pkgs.xdg-desktop-portal-wlr
    pkgs.xdg-desktop-portal-gtk
    pkgs.xdg-desktop-portal-hyprland
    pkgs.wlr-randr
    pkgs.wl-clipboard
    pkgs.hyprland-protocols
    pkgs.grim
    pkgs.slurp
    pkgs.uwsm
    pkgs.fastfetch
    pkgs.git
    pkgs.gcc
    pkgs.zip
    pkgs.unzip
    pkgs.pulseaudio
    pkgs.brightnessctl
    pkgs.pavucontrol
    pkgs.chromium
    pkgs.logmein-hamachi
    pkgs.bluez
    pkgs.p7zip
    pkgs.exiftool
    pkgs.yara
    pkgs.tinyxxd
    pkgs.wireshark
    pkgs.tshark
    pkgs.wf-recorder
    pkgs.tree
    pkgs.stegseek
    pkgs.netcat
    pkgs.sonic-visualiser
    pkgs.sleuthkit
    pkgs.ntfs3g
    pkgs.binwalk
    pkgs.bombardier
    pkgs.file
    pkgs.upower
    pkgs.dmidecode
    pkgs.volatility3
    pkgs.evtx
    pkgs.hashcat
    pkgs.ghidra
    pkgs.elf-info
    pkgs.foremost
    pkgs.ffmpeg
    pkgs.audacity
    pkgs.id3v2
    pkgs.gdb
    pkgs.ghex
    pkgs.sox
    pkgs.powertop
    pkgs.inspectrum
    pkgs.qsstv
    pkgs.csvkit
    pkgs.saleae-logic-2
    pkgs.pev
    pkgs.xortool
    pkgs.vimPlugins.clangd_extensions-nvim
    pkgs.clang-tools
    pkgs.gnumake
    pkgs.gnupg
    pkgs.zsteg
    pkgs.pgpdump
    pkgs.pdf-parser
    pkgs.steghide
    pkgs.bento4
    pkgs.john
    pkgs.fcrackzip
    pkgs.oletools
    pkgs.bkcrack
    pkgs.wireguard-tools
    pkgs.flameshot
    pkgs.tulip
    pkgs.nix-tree
    pkgs.desktop-file-utils
    pkgs.mattermost
    pkgs.wineWowPackages.stagingFull
    pkgs.gearlever
    pkgs.unrar
    pkgs.zathura
    pkgs.nbd
    pkgs.docker-compose
    pkgs.pngcheck
    pkgs.go
    pkgs.openvpn
    pkgs.openssh
    pkgs.automake
    pkgs.autoconf
    pkgs.libtool
    pkgs.gnum4
    pkgs.jq
    pkgs.dwarf2json
  ];
}
