background {
    monitor =
    path = /home/grey/.config/hypr/wall/ricefield.png 
    blur_passes = 1
}

# Profile Picture
image {
     monitor =
     path = /home/grey/.config/hypr/wall/renge-drinkmilk-cropped.jpg
     size = 256
     border_size = 0
     rounding = 40
     position = 0, -50
     halign = center
     valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -300
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(209, 207, 207, 0.75)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = rgba(209, 207, 207, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}

# BATTERY
label {
  monitor =
  text = cmd[update:60000] ~/.config/hypr/bat.sh
  color = rgba(209, 207, 207, 0.75)
  font_size = 20
  font_family = JetBrains Mono
  position = -30, -30
  halign = right
  valign = bottom
}

